# Generated by Django 5.2.1 on 2025-05-11 05:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchaeologicalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='遗址名称')),
                ('location_description', models.TextField(blank=True, null=True, verbose_name='地理位置描述')),
                ('period', models.CharField(blank=True, max_length=100, null=True, verbose_name='年代')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='地理坐标')),
                ('protection_level', models.CharField(choices=[('national_1', '国家级-一级'), ('national_2', '国家级-二级'), ('national_3', '国家级-三级'), ('national', '国家级'), ('provincial', '省级'), ('municipal', '市级'), ('county', '县级'), ('other', '其他'), ('unknown', '未定级')], default='unknown', max_length=20, verbose_name='文物保护级别')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='所在省份')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='所在城市')),
                ('county_district', models.CharField(blank=True, max_length=50, null=True, verbose_name='所在区县')),
                ('description', models.TextField(blank=True, null=True, verbose_name='遗址简介')),
                ('gallery_urls', models.TextField(blank=True, null=True, verbose_name='图片画廊URL列表 (每行一个URL)')),
                ('discovered_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='发现者/单位')),
                ('discovery_date', models.DateField(blank=True, null=True, verbose_name='发现年代/日期')),
                ('excavation_info', models.TextField(blank=True, null=True, verbose_name='发掘信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '考古遗址',
                'verbose_name_plural': '考古遗址',
                'ordering': ['name'],
            },
        ),
    ]
