# Generated by Django 5.2.1 on 2025-05-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruins_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archaeologicalsite',
            name='protection_batch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='文保批次'),
        ),
    ]
